# Generated by Django 2.2.6 on 2019-10-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('nombre_real', models.CharField(max_length=128)),
                ('imagen', models.ImageField(upload_to='')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
